[package]
org = "ballerinax"
name = "sap"
version = "@toml.version@"
distribution = "2201.8.0"
authors = ["Ballerina"]
repository = "https://github.com/ballerina-platform/module-ballerinax-sap"
license = ["Apache-2.0"]

[build-options]
observabilityIncluded = true

[platform.java17]
graalvmCompatible = true

[[platform.java17.dependency]]
groupId = "io.ballerina.lib.sap"
artifactId = "sap-native-@project.version@"
version="@project.version@"
path = "../native/build/libs/sap-native-@project.version@.jar"
