[package]
org = "ballerinax"
name = "sap"
version = "0.1.0"
distribution = "2201.8.0"
authors = ["Ballerina"]
repository = "https://github.com/ballerina-platform/module-ballerinax-sap"
license = ["Apache-2.0"]

[build-options]
observabilityIncluded = true

[platform.java17]
graalvmCompatible = true
