[package]
org = "ballerinax"
name = "sap"
version = "1.0.1"
distribution = "2201.9.0"
authors = ["Ballerina"]
keywords = ["Business Management/ERP", "Cost/Paid"]
export = ["sap"]
repository = "https://github.com/ballerina-platform/module-ballerinax-sap"
icon = "icon.png"
license = ["Apache-2.0"]

[build-options]
observabilityIncluded = true

[platform.java17]
graalvmCompatible = true

[[platform.java17.dependency]]
groupId = "io.ballerina.lib.sap"
artifactId = "sap-native-1.0.1-SNAPSHOT"
version="1.0.1-SNAPSHOT"
path = "../native/build/libs/sap-native-1.0.1-SNAPSHOT.jar"
