[package]
org = "wso2"
name = "pending_order_reminder"
version = "0.1.0"
distribution = "2201.9.0"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "ballerinax"
name = "sap"
version = "1.0.1"
repository = "local"
