name: Build

on:
  push:
    branches:
      - main
      - 2201.[0-9]+.x
  repository_dispatch:
    types: check_connector_for_breaking_changes

jobs:
  call_workflow:
    name: Run Connector Build Workflow
    if: ${{ github.repository_owner == 'ballerina-platform' }}
    uses: ballerina-platform/ballerina-library/.github/workflows/build-connector-template.yml@main
    secrets: inherit
    with:
      repo-name: module-ballerinax-sap
      additional-build-flags: "-x :sap-examples:build"
      additional-test-flags: "-x :sap-examples:test -Pdisable=sap"
